#pragma once

#define D_SOUND_MAX 4

#define D_PHONE_WIDTH 480
#define D_PHONE_HEIGHT 800

#define D_SCREEN_SCALE_WIDTH(s) (D_PHONE_WIDTH/100) * s
#define D_SCREEN_SCALE_HEIGHT(s) (D_PHONE_HEIGHT/100) * s

#define D_BLOCKMAP_WIDTH 7
#define D_BLOCKMAP_HEIGHT 11

#define	D_LINE_START_X -192.0f
#define	D_LINE_START_Y 340.0f
#define D_LINE_END_Y -300.0f

#define D_CALC_START_X -224
#define D_CALC_START_Y 372

#define D_LOGOVIB_MAX 8

#define D_CAM_Z_FIXED 695.0f


#define D_SCORE_CREATEBLOCK 3

#define D_SCORE_ICEBLOCK 3

#define D_SCORE_EROSIONBLOCK 1

#define D_BLOCK_SPEED 400.0f
#define D_BLOCK_PLUSSPEED 60.0f

#define D_EROSIONTIME 4.0f
#define D_FREEZETIME 2.0f

#define D_BLOCK_WIDTH 64
#define D_BLOCK_HEIGHT 64

#define D_SOUND_ICE_CHANNEL 5

#define D_INTERFACE_START_X 40

#define D_INTERFACE_NOWBLOCK_TEXT_Y 120
#define D_INTERFACE_MOUSELIST_TEXT_Y 140
#define D_INTERFACE_EROSIONSPEED_TEXT_Y 160
#define D_INTERFACE_CREATETIME_TEXT_Y 205
#define D_INTERFACE_EROSIONPLUSSPEED_TEXT_Y 260
#define D_INTERFACE_FREEMOVE_TEXT_Y 300

#define D_GAMEOVER_BLINDTIME 1.5f

#define D_INTERFACE_X -190

#define D_BLOCK_NUMBER 3

#define D_STAGEMENU_START_X - 150.0f
#define D_STAGEMENU_START_Y   300.0f

#define D_STAGEMENU_DISTANCE 150.0f

#define D_SNOW_RAND_POS_X 300.0f + CEMMath::RandomFloatInRange(300.0f ,600.0f)
#define D_SNOW_RAND_POS_Y 300.0f + CEMMath::RandomFloatInRange(-200.0f ,600.0f);

#define D_SNOW_MAX 3

#define D_COMBOTIME 2.0f